mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mysite.core import views


urlpatterns = [
    path('', views.home, name='home'),
    path('upload/', views.upload, name='upload'),
    path('signup/', views.signup, name='signup'),
    path('secret/', views.secret_page, name='secret'),
    path('secret2/', views.SecretPage.as_view(), name='secret2'),
    path('accounts/', include('django.contrib.auth.urls')),
    
    
    path('books/', views.book_list, name='book_list'),
    path('books/<int:pk>/viewdetail', views.order_detailview, name='order_detailview'),
    path('books/<int:pk>/ticket_viewdetail', views.ticket_detailview, name='ticket_detailview'),
    path('books/<int:pk>/deletebook', views.delete_book, name='delete_book'),
    path('books/create/', views.upload_book, name='upload_book'),
    path('books/<int:pk>/addtrip/', views.create_trips, name='create_trips'),
    path('books/<int:pk>/delete/', views.delete_trip, name='delete_trip'),



    path('class/books/', views.BookListView.as_view(), name='class_book_list'),
    path('class/books/upload/', views.UploadBookView.as_view(), name='class_upload_book'),



    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/core/models.py
from django.db import models
from django.contrib.auth.models import User
from mysite.choices import *

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    pdf = models.FileField(upload_to='books/pdfs/')
    cover = models.ImageField(upload_to='books/covers/', null=True, blank=True)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.pdf.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)

class BookRazdel(models.Model):
    book = models.ForeignKey(Book, blank=True, null=True, default=None,on_delete=models.CASCADE)
    razdel = models.CharField(max_length=64, blank=False, null=True, default=None)


    def __str__(self):
        return self.razdel



class Customer(models.Model):
    #user = models.ForeignKey(User, blank=True, null=True, default=None,on_delete=models.CASCADE)

    customer_lastname = models.CharField(max_length=64, blank=False, null=True, default=None)
    customer_firstname = models.CharField(max_length=64, blank=False, null=True, default=None)
    customer_patronymic = models.CharField(max_length=64, blank=False, null=True, default=None)
    customer_email = models.EmailField(blank=True, null=True, default=None)
    customer_phone = models.CharField(max_length=10, blank=False, null=True, default=None)
    #паспорт
    customer_id_number = models.DecimalField(max_digits=10,decimal_places=0,blank=False,null=True, default=None)
    #дата рождения
    customer_bday = models.DateField(blank=False, null=True, default=None)
    #должность
    customer_position = models.CharField(max_length=64, blank=False, null=True, default=None)
    #подразделение
    customer_division = models.CharField(max_length=64, blank=False, null=True, default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s %s %s" % (self.customer_lastname, self.customer_firstname, self.customer_patronymic)

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

# class Status(models.Model):
#     name = models.IntegerField(choices=STATUS_CHOICES, default=1)
#
#     is_active = models.BooleanField(default=True)
#     created = models.DateTimeField(auto_now_add=True, auto_now=False)
#     updated = models.DateTimeField(auto_now_add=False, auto_now=True)
#
#     def __str__(self):
#         return  self.name
#
#     class Meta:
#         verbose_name = 'Статус заказа'
#         verbose_name_plural = 'Статусы заказа'

class Order(models.Model):

    user = models.ForeignKey(User, blank=True, null=True, default=None,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,blank=False, null=True, on_delete=models.CASCADE,default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    # status = models.ForeignKey(Status,on_delete=models.CASCADE)
    status =  models.IntegerField(choices=STATUS_CHOICES, default=1)
    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "Заказ %s %s" % (self.id, self.status)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def save(self, *args, **kwargs):

        super(Order, self).save(*args, **kwargs)


class TripInOrder(models.Model):

    order = models.ForeignKey(Order, blank=True, null=False, default=None,on_delete=models.CASCADE)
    date_of_trip = models.DateField(blank=False,null=True, default=None)
    time_of_trip = models.IntegerField(choices=TIME_CHOICES, default=0)
    departure = models.CharField(max_length=50, blank=True, null=True, default=None)
    arrival = models.CharField(max_length=50, blank=True, null=True, default=None)
    ticket_number = models.CharField(max_length=24, blank=True, null=True, default=None)
    flight_number = models.CharField(max_length=24, blank=True, null=True, default=None)
    comments = models.TextField(blank=True, null=True, default=None)
    # status = models.ForeignKey(Status, on_delete=models.CASCADE,default=None,null=True)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    pdf = models.FileField(upload_to='books/pdfs/',blank=True, null=True, default=None)

    is_active = models.BooleanField(default=True)

    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s %s %s" % (self.date_of_trip.strftime('%Y-%m-%d'), self.departure, self.arrival)

    class Meta:
        verbose_name = 'Поездка'
        verbose_name_plural = 'Поездки'

mysite/core/forms.py
from django import forms
from mysite.choices import *

import datetime

from .models import Book, Order, TripInOrder

class OrderForm(forms.ModelForm):

    status = forms.ChoiceField(choices=STATUS_CHOICES, label="", initial='', widget=forms.Select(), required=True)
    class Meta:
        model = Order
        exclude = ('updated','comments')
        widgets = {'user': forms.HiddenInput()}



class DateInput(forms.DateInput):
    input_type = 'date'



class TripInOrderForm(forms.ModelForm):

    status = forms.ChoiceField(choices=STATUS_CHOICES, label="", initial='', widget=forms.Select(), required=True)

    class Meta:
        model = TripInOrder
        exclude = ('updated',)
        widgets = {
            'date_of_trip': DateInput(),
            'order': forms.HiddenInput()

        }

    date_of_trip = forms.DateField(widget=DateInput, initial=datetime.date.today)

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'pdf', 'cover')

mysite/core/views.py
from django.shortcuts import render, redirect, render_to_response
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView, ListView, CreateView
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy

from .forms import BookForm
from .forms import OrderForm
from .forms import TripInOrderForm

from .models import Book
from .models import Order
from .models import TripInOrder

from mysite.choices import *

# class Home(TemplateView):
#     count = User.objects.count()
#     template_name = 'home.html'
#     return render(request, 'home.html', {
#         'count': count
#     })

def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)
    return render(request, 'upload.html', context)

@login_required
def book_list(request):
    orders = Order.objects.all()
    return render(request, 'book_list.html', {
        'orders': orders
    })


def upload_book(request):

    if request.method == 'POST':

        form = OrderForm(request.POST, request.FILES,initial={'user': request.user})

        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = OrderForm(initial={'user': request.user})

    return render(request, 'upload_book.html', {
        'form': form
    })

def order_detailview(request,pk):
    order = Order.objects.get(pk=pk)

    if request.method == 'POST':

        form = OrderForm(request.POST, instance=order)

        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = OrderForm(instance=order)


    return render(request, 'order_detail.html', {
        'form': form
    })

def ticket_detailview(request,pk):
    ticket = TripInOrder.objects.get(pk=pk)

    if request.method == 'POST':

        form = TripInOrderForm(request.POST, request.FILES, instance=ticket)

        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = TripInOrderForm(instance=ticket)


    return render(request, 'ticket_detail.html', {
        'form': form
    })

def delete_book(request, pk):
    if request.method == 'POST':
        book = Order.objects.get(pk=pk)
        book.delete()
    return redirect('book_list')

def delete_trip(request, pk):
    if request.method == 'POST':
        book = TripInOrder.objects.get(pk=pk)
        book.delete()
    return redirect('book_list')

def create_trips(request, pk):

    order = Order.objects.get(pk=pk)

    if request.method == 'POST':

        form = TripInOrderForm(request.POST or None, initial={'order': order})

        if form.is_valid():
            form.save()

            return redirect('book_list')

    else:
        form = TripInOrderForm(initial={'order': order})

    return render(request, 'create_trips.html', {
        'form': form
    })

class BookListView(ListView):
    model = Order
    template_name = 'class_book_list.html'
    context_object_name = 'books'


class UploadBookView(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('class_book_list')
    template_name = 'upload_book.html'

def home(request):
    count = Order.objects.count()
    return render(request, 'home.html', {
        'count': count
    })


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form
    })


@login_required
def secret_page(request):
    return render(request, 'secret_page.html')


class SecretPage(LoginRequiredMixin, TemplateView):
    template_name = 'secret_page.html'

mysite/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>{% block title %}Полюс webapp{% endblock %}</title>
  <style type="text/css">
    .asteriskField {
      display: none;
    }

    form .alert ul li {
      list-style: none;
    }

    form .alert ul {
      padding: 0;
      margin: 0;
    }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Организация</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          {% if user.is_authenticated %}
{#            <li class="nav-item">#}
{#              <a class="nav-link" href="{% url 'upload' %}">Simple Upload</a>#}
{#            </li>#}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'book_list' %}">Журнал заявок</a>
            </li>
{#            <li class="nav-item">#}
{#            <a class="nav-link" href="{% url 'class_book_list' %}">Model Forms Upload (CBV)</a>#}
{#          </li>#}
          {% endif %}
        </ul>
        {% if user.is_authenticated %}
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
              </div>
            </li>
          </ul>
        {% else %}
          <form class="form-inline my-2 my-lg-0">
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
          </form>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="footer">


  </div>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

mysite/templates/book_list.html
{% extends 'base.html' %}

{% block content %}

  {% block content_header %}
    <h2>Заявки на приобретение билетов</h2>
    <p>
      <a href="{% url 'upload_book' %}" class="btn btn-primary">Создать заявку</a>
    </p>
  {% endblock %}

  <table class="table mb-0">
    <thead>
      <tr>
          <th>-</th>
          <th>Номер</th>
          <th>Дата</th>
          <th>Сотрудник</th>
          <th>Статус</th>

          <th>Время</th>
          <th>-</th>

      </tr>
    </thead>
    <tbody>
    {% for order in orders %}
        {% if user == order.user or user.is_staff or user.is_superuser %}
        <tr>|
            <td><b>{{ order.is_active }}</b></td>
            <td><a href="{% url 'order_detailview' order.pk %}">edit</a></td>
            <td><b>{{ order.id|stringformat:'06d'}}</b></td>
            <td><b>{{ order.created|date:"d/m/Y" }}</b></td>
            <td><b>{{ order.customer }}</b></td>

            {% if order.status == 1 %}
            <td><b>новый</b></td>
                {% elif order.status == 2 %}
            <td><b>в работе</b></td>
                {% elif order.status == 3 %}
            <td><b>выполнен</b></td>
                {% elif order.status == 4 %}
            <td><b>отменен</b></td>
            {% endif %}

            <td>{{ order.comment }}</td>
            <td>
            <td><a href="{% url 'create_trips' order.pk %}">добавить поездку</a></td>

{#            <td>#}
<!--            <form method="post" action="{% url 'create_trips' order.pk %}">-->
<!--              {% csrf_token %}-->
<!--              <button type="submit" class="btn btn-primary btn-sm">добавить поездку</button>-->
<!--            </form>-->
{#          </td>#}
          <td>
            <form method="post" action="{% url 'delete_book' order.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
          </td>

        </tr>
          {% for tripinorder in order.tripinorder_set.all %}
              <tr>
                  <td></td>
                  <td><a href="{% url 'ticket_detailview' tripinorder.pk %}">edit</a></td>

              <td>{{ tripinorder.pk|stringformat:'06d' }}</td>
                  <td>{{ tripinorder.date_of_trip|date:"d/m/Y" }}</td>
            <td>{{ tripinorder.departure}}  -->  {{tripinorder.arrival}} </td>

                  {% if tripinorder.status == 1 %}
            <td>новый</td>
                {% elif tripinorder.status == 2 %}
            <td>в работе</td>
                {% elif tripinorder.status == 3 %}
            <td>выполнен</td>
                {% elif tripinorder.status == 4 %}
            <td>отменен</td>
            {% endif %}

             {% if tripinorder.time_of_trip == 0 %}
            <td>Любое время</td>
                {% elif tripinorder.time_of_trip == 1 %}
            <td>Ночь (00:00 - 06:00)</td>
                {% elif tripinorder.time_of_trip == 2 %}
            <td>Утро (06:00 - 12:00)</td>
                {% elif tripinorder.time_of_trip == 3 %}
            <td>День (12:00 - 18:00)</td>
                 {% elif tripinorder.time_of_trip == 4 %}
            <td>Вечер(18:00 - 24:00)</td>
            {% endif %}


                  <td></td>
            <td>
                {% if tripinorder.pdf %}
            <a href="{{ tripinorder.pdf.url }}" class="btn btn-primary btn-sm" target="_blank">
              Скачать билет
            </a>
                    {% else %}
                    <p>-</p>
                {% endif %}
            </td>
              <td>
            <form method="post" action="{% url 'delete_trip' tripinorder.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
          </td>
              </tr>
        {% endfor %}

        {% endif %}
      {% endfor %}

    </tbody>
  </table>
{% endblock %}

mysite/templates/class_book_list.html
{% extends 'book_list.html' %}

{% block content_header %}
  <h2>Books (Class-Based View)</h2>
  <p>
    <a href="{% url 'class_upload_book' %}" class="btn btn-primary">Upload book</a>
  </p>
{% endblock %}

mysite/templates/create_trips.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>Добавить поездку</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}


    <button type="submit" class="btn btn-primary">Ok</button>
  </form>
{% endblock %}

mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Домашняя страница</h2>
  <p>Добро пожаловать в сервис заказа поездок, {% if user.is_authenticated %}{{ user.username }}{% else %}гость{% endif %}!</p>
  <p>
    <strong>Общее число заявок: </strong> {{ count }}
  </p>
{% endblock %}

mysite/templates/order_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1>Заявка № {{ form.instance.id|stringformat:'06d' }}</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Ok</button>

{% endblock %}

mysite/templates/secret_page.html
{% extends 'base.html' %}

{% block content %}
  <p>This is a secret page!</p>
  <br>
  <p>Здесь вы можете оформить билеты для себя и своих подчиненных</p>
{% endblock %}

mysite/templates/ticket_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1>Поездка № {{ form.instance.id|stringformat:'06d' }}</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Ok</button>

{% endblock %}

mysite/templates/upload.html
{% extends 'base.html' %}

{% block content %}
  <h2>Upload</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="document">
    <button type="submit">Upload file</button>
  </form>
  {% if url %}
    <p>Uploaded file: <a href="{{ url }}">{{ url }}</a></p>
  {% endif %}
{% endblock %}

mysite/templates/upload_book.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>Создать заявку</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Ok</button>
  </form>
{% endblock %}